// bus事件
module.exports = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS', // 登录成功事件
  PUBLISH_MATERIAL_SUCCESS: 'PUBLISH_MATERIAL_SUCCESS', // 发布素材成功事件
  SELECT_GOODS_SUCCESS: 'SELECT_GOODS_SUCCESS', // 选择商品成功事件
  SET_PWD_SUCCESS: 'SET_PWD_SUCCESS', // 设置密码成功事件
  ORDER_LIST_REFLUSH: 'ORDER_LIST_REFLUSH', //订单列表刷新
  ORDER_DETAIL_REFLUSH: 'ORDER_DETAIL_REFLUSH', //订单详情刷新
  RETURN_LIST_REFLUSH: 'RETURN_LIST_REFLUSH', //退换列表刷新
  SAVE_REALNAME_SUCCESS: 'SAVE_REALNAME_SUCCESS', // 保存实名信息成功
  RETURN_DETAIL_REFLUSH:'RETURN_DETAIL_REFLUSH', //退单详情刷新
  SELECT_COUPON: 'SELECT_COUPON', // 选择优惠券
  ADD_CART_SUCCESS:'ADD_CART_SUCCESS' // 添加购物车成功
}